'use strict';
const $ = (s) => document.querySelector(s);
let state = {models: [], jobs: [], hardware: {}}, currentPage = 'home', kind = 'image', uploaded = '', token = '', toastTimer, lastJobs = '', previewJob = '', pollBusy = false;
const palette = {image:['#c0a4ff','#2b233a','#49375f'],music:['#eab49c','#332723','#523b30'],video:['#9aacdc','#222a3a','#334058'],mesh:['#97d4c7','#20302e','#314b45'],cutout:['#d8c389','#302c20','#4a4330']};
const statuses = {queued:'Queued',running:'Running',cancelling:'Cancelling',cancelled:'Cancelled',completed:'Complete',failed:'Failed',interrupted:'Interrupted'};
// Display older system messages in English without changing saved jobs or user prompts.
function jobMessage(job){const message=job.message||'';if(!/[\uac00-\ud7a3]/.test(message))return message;if(job.status==='completed')return job.action==='install'?'Installation complete':'Generation complete · GPU memory released';return (statuses[job.status]||'Job status')+' · check the log for details.';}
const icons = Object.fromEntries(Object.entries(palette).map(([k])=>[k,'']));
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),6500);}
async function api(path,payload){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
function show(page){currentPage=page;document.querySelectorAll('.page').forEach(e=>e.classList.toggle('hidden',e.id!=='page-'+page));document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===page));document.querySelectorAll('.tool-nav').forEach(e=>e.classList.toggle('active',page==='studio'&&e.dataset.kind===kind));$('#breadcrumb').textContent=({home:'Workspace',models:'Model management',gallery:'Results',studio:state.models.find(m=>m.id===kind)?.name})[page];window.scrollTo(0,0);}
function accent(e,id){const p=palette[id];e.style.setProperty('--accent',p[0]);e.style.setProperty('--accent-bg',p[1]);e.style.setProperty('--accent-line',p[2]);}
function modelIcon(m){const e=node('span','tool-icon',m.icon);accent(e,m.id);return e;}
function isInstalling(id){return state.jobs.some(j=>j.kind===id&&j.action==='install'&&['queued','running','cancelling'].includes(j.status));}
function cards(){const cards=$('#cards'),nav=$('#toolNav');cards.replaceChildren();nav.replaceChildren();for(const m of state.models){const card=node('button','tool-card');card.type='button';accent(card,m.id);card.append(modelIcon(m),node('span','arrow','↗'),node('h3','',m.name),node('p','',m.description));const line=node('div','model-name');line.append(node('span','',m.model),node('span','',m.id==='cutout'?'CPU':'8GB mode'));card.append(line,node('span','card-status',m.installed?'Installed':'Not installed'));card.onclick=()=>openStudio(m.id);cards.append(card);const button=node('button','tool-nav');button.dataset.kind=m.id;button.append(node('span','',m.icon),document.createTextNode(m.name));button.onclick=()=>openStudio(m.id);nav.append(button);}}
function models(){const list=$('#modelList');list.replaceChildren();for(const m of state.models){const row=node('div','model-row');row.append(modelIcon(m));const detail=node('div','model-details');detail.append(node('h3','',m.model),node('p','',m.vram),node('p','',m.license),node('p','',m.commercial_note));const a=node('a','', 'Official model and license ↗');a.href=m.source;a.target='_blank';a.rel='noopener';detail.append(a);row.append(detail);const action=node('div','model-install');action.append(node('small','',`Required free space: about ${m.disk_gb}GB + 3GB`));const button=node('button',m.installed?'secondary':'primary',m.installed?'Reinstall':isInstalling(m.id)?'Installing…':'↓ Install model');button.disabled=isInstalling(m.id);button.onclick=()=>installModel(m.id);action.append(button);row.append(action);list.append(row);}$('#diskInfo').textContent=`Available disk space: ${state.hardware.free_disk_gb??'—'}GB`;}
async function installModel(id){try{await api('/api/jobs',{kind:id,action:'install'});toast('Installation queued. Check progress and logs below.');await refresh();}catch(e){toast(e.message);}}
function openStudio(id){kind=id;uploaded='';$('#upload').value='';$('#uploadPreview').classList.add('hidden');const m=state.models.find(x=>x.id===id);$('#studioModel').textContent=m.model.toUpperCase();$('#studioTitle').textContent=m.name;$('#studioDescription').textContent=m.description;$('#commercialHint').textContent='Commercial use permitted · '+(m.commercial_note||'Follow the original license terms.')+' A usage notice is saved with each result.';$('#prompt').value='';$('#prompt').maxLength=id==='music'?512:1500;$('#promptField').classList.toggle('hidden',m.input);$('#uploadField').classList.toggle('hidden',!m.input);$('#imageFields').classList.toggle('hidden',m.input);$('#imageSizeField').classList.toggle('hidden',id!=='image');$('#negativeField').classList.toggle('hidden',id!=='image');$('#musicFields').classList.toggle('hidden',id!=='music');$('#videoHint').classList.toggle('hidden',id!=='video');$('#inputHint').textContent=id==='mesh'?'Use an image with one large, centered object. The background is removed automatically. GLB includes colors; OBJ color display depends on your viewer.':'The result is saved as a transparent PNG.';previewJob='';emptyPreview();studioState();show('studio');}
function studioState(){if(!state.models.length)return;const m=state.models.find(x=>x.id===kind);$('#engineState').textContent=m.installed?'● Model ready':isInstalling(kind)?'○ Installing':'○ Not installed';$('#generate').disabled=!m.installed;$('#installHint').classList.toggle('hidden',m.installed);$('#installHint').replaceChildren();if(!m.installed){$('#installHint').append(node('span','',`Install ${m.model} first. Required free space: about ${m.disk_gb}GB + 3GB required.`));const button=node('button','secondary',isInstalling(kind)?'Installing…':'↓ Install this model');button.disabled=isInstalling(kind);button.type='button';button.onclick=()=>installModel(kind);$('#installHint').append(button);}}
function emptyPreview(){const e=node('div','empty-preview');e.append(node('span','','✧'),node('strong','','Start with an idea.'),node('p','','Your finished results will appear here.'));$('#preview').replaceChildren(e);$('#previewTag').textContent='READY WHEN YOU ARE';}
function downloads(files){const div=node('div','downloads');for(const file of files){const a=node('a','',`↓ ${file.name}`);a.href=file.url;a.download=file.name;div.append(a);}return div;}
function media(job,full=false){const file=job.files.find(f=>/\.(png|wav|mp4)$/.test(f.name));if(file){let e;if(file.name.endsWith('.png')){e=node('img');e.src=file.url;e.alt=job.prompt||'Background removal result';e.loading='lazy';}else{e=node(file.name.endsWith('.wav')?'audio':'video');e.src=file.url;e.controls=true;e.preload='metadata';}return e;}if(job.kind==='mesh'&&full){const canvas=node('canvas','mesh-preview');const file=job.files.find(f=>f.name.endsWith('.obj'));if(file)loadMesh(canvas,file.url);return canvas;}const e=node('div','empty-preview');e.style.minHeight='170px';e.append(node('span','','⬡'),node('strong','','3D asset · GLB / OBJ'));return e;}
function preview(job){previewJob=job.id;$('#previewTag').textContent='GENERATED LOCALLY';$('#preview').replaceChildren(media(job,true),downloads(job.files));if(job.metrics){$('#preview').append(node('p','hint',`${job.metrics.seconds}s · Seed ${job.metrics.seed} · Peak GPU allocation ${job.metrics.peak_vram_gb}GB`));}}
function gallery(){const list=$('#gallery');list.replaceChildren();const jobs=state.jobs.filter(j=>j.status==='completed'&&j.action==='generate');$('#resultCount').textContent=jobs.length;if(!jobs.length){const e=node('div','queue-empty','No completed results yet. Choose a tool to create your first asset.');e.style.gridColumn='1 / -1';list.append(e);return;}for(const j of jobs){const e=node('article','gallery-item');e.append(media(j));const detail=node('div');const m=state.models.find(m=>m.id===j.kind);detail.append(node('h3','',m.name),node('small','',new Date(j.created*1000).toLocaleString('en-US')),node('p','',j.prompt||'Generated from an input image'));detail.append(downloads(j.files));const button=node('button','text-button','Open preview ↗');button.onclick=()=>{openStudio(j.kind);preview(j);};detail.append(button);e.append(detail);list.append(e);}}
function queue(){const list=$('#queue');list.replaceChildren();$('#queueCount').textContent=state.jobs.filter(j=>['queued','running','cancelling'].includes(j.status)).length;if(!state.jobs.length){list.append(node('div','queue-empty','No queued jobs. What would you like to create?'));return;}for(const j of state.jobs.slice(0,12)){const row=node('div','queue-row '+j.status);const m=state.models.find(m=>m.id===j.kind);row.append(node('span','queue-icon',m.icon));const detail=node('div','queue-content');detail.append(node('strong','',`${m.name}${j.action==='install'?' · Model installation':''}`),node('p','',jobMessage(j)));if(j.status==='running'){const track=node('div','progress');const bar=node('div');bar.style.width=Math.min(100,j.progress)+'%';track.append(bar);detail.append(track);}if(j.metrics)detail.append(node('small','',`${j.metrics.seconds}s · Peak GPU allocation ${j.metrics.peak_vram_gb}GB`));row.append(detail,node('span','status-tag',statuses[j.status]));if(['queued','running'].includes(j.status)){const button=node('button','secondary','Cancel');button.onclick=async()=>{try{await api('/api/cancel',{id:j.id});await refresh();}catch(e){toast(e.message);}};row.append(button);}else if(j.status==='completed'&&j.action==='generate'){const button=node('button','secondary','Open');button.onclick=()=>{openStudio(j.kind);preview(j);};row.append(button);}const log=node('a','text-button','Log ↗');log.href='/logs/'+j.id+'.log';log.target='_blank';row.append(log);list.append(row);}}
async function refresh(){if(pollBusy)return;pollBusy=true;try{const response=await fetch('/api/state');if(!response.ok)throw new Error('Server request failed');const data=await response.json();token=data.token;const modelChanged=JSON.stringify(data.models)!==JSON.stringify(state.models);state=data;const h=state.hardware;$('#gpuName').textContent=h.gpu?.name||'Check your NVIDIA GPU';$('#gpuMemory').textContent=h.gpu?`${(h.gpu.used_mb/1024).toFixed(1)} / ${(h.gpu.total_mb/1024).toFixed(1)}GB in use`:'Background removal uses CPU';if(modelChanged){cards();models();studioState();}$('#diskInfo').textContent=`Available disk space: ${h.free_disk_gb}GB`;const fingerprint=JSON.stringify(state.jobs);if(fingerprint!==lastJobs){lastJobs=fingerprint;queue();gallery();models();studioState();}const j=state.jobs.find(x=>x.id===previewJob);if(j?.status==='completed'&&$('#previewTag').textContent!=='GENERATED LOCALLY')preview(j);else if(j&&['running','queued','failed','cancelled','cancelling'].includes(j.status)){$('#previewTag').textContent=statuses[j.status];const strong=$('#preview strong'),p=$('#preview p');if(strong)strong.textContent=jobMessage(j);if(p)p.textContent=j.status==='failed'?'Check the job log below for details.':'Check progress in the queue.';}}catch(e){$('#gpuName').textContent='Disconnected from the app';}finally{pollBusy=false;}}
$('#generationForm').onsubmit=async(e)=>{e.preventDefault();if(state.models.find(m=>m.id===kind).input&&!uploaded){toast('Select an input image first.');return;}$('#generate').disabled=true;try{const j=await api('/api/jobs',{kind,action:'generate',prompt:$('#prompt').value,negative:$('#negative').value,seed:Number($('#seed').value),size:Number($('#size').value),duration:Number($('#duration').value),instrumental:$('#instrumental').value==='true',lyrics:$('#lyrics').value,upload:uploaded});emptyPreview();previewJob=j.id;toast('Generation queued.');await refresh();}catch(err){toast(err.message);}finally{studioState();}};
$('#upload').onchange=async()=>{const file=$('#upload').files[0];if(!file)return;if(file.size>20*1024*1024){toast('Select an image no larger than 20MB.');return;}try{const raw=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/upload',{name:file.name,data:raw.split(',')[1]});uploaded=result.upload;$('#uploadPreview').src=result.url;$('#uploadPreview').classList.remove('hidden');toast('Input image ready.');}catch(e){toast(e.message);}};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));$('.brand').onclick=(e)=>{e.preventDefault();show('home');};$('#back').onclick=()=>show('home');$('#heroStart').onclick=()=>openStudio('image');$('#example').onclick=()=>{$('#prompt').value=state.models.find(m=>m.id===kind).example;};$('#openResults').onclick=()=>api('/api/open-results',{}).catch(e=>toast(e.message));$('#exit').onclick=async()=>{try{await api('/api/shutdown',{});toast('The app has closed. You can close this tab.');}catch(e){toast(e.message);}};
// Offline OBJ viewer: drag to rotate. It previews actual generated geometry.
async function loadMesh(canvas,url){try{const response=await fetch(url);if(!response.ok)throw new Error('Unable to read the 3D file.');const text=await response.text();let vertices=[],faces=[];for(const line of text.split('\n')){const items=line.trim().split(/\s+/);if(items[0]==='v'){vertices.push(items.slice(1).map(Number));}else if(items[0]==='f'){const indices=items.slice(1).map(x=>Number(x.split('/')[0])-1);for(let i=1;i<indices.length-1;i++)faces.push([indices[0],indices[i],indices[i+1]]);}}if(!vertices.length||!faces.length)return;const bounds=[[Infinity,-Infinity],[Infinity,-Infinity],[Infinity,-Infinity]];for(const v of vertices)for(let a=0;a<3;a++){bounds[a][0]=Math.min(bounds[a][0],v[a]);bounds[a][1]=Math.max(bounds[a][1],v[a]);}const center=bounds.map(b=>(b[0]+b[1])/2),radius=Math.max(...bounds.map(b=>b[1]-b[0]))/2||1;vertices=vertices.map(v=>[(v[0]-center[0])/radius,(v[2]-center[2])/radius,-(v[1]-center[1])/radius,...v.slice(3)]);let yaw=.5,pitch=-.2,drag=null;const ctx=canvas.getContext('2d');function draw(){canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;const w=canvas.width,h=canvas.height,scale=Math.min(w,h)*.34;ctx.fillStyle='#101018';ctx.fillRect(0,0,w,h);const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);const points=vertices.map(v=>{const x=v[0]*cy-v[2]*sy,z=v[0]*sy+v[2]*cy,y=v[1]*cp-z*sp;return [w/2+x*scale,h/2-y*scale,v[1]*sp+z*cp];});const triangles=faces.map(f=>({f,z:f.reduce((s,i)=>s+points[i][2],0)/3})).sort((a,b)=>a.z-b.z);for(const {f} of triangles){const a=points[f[0]],b=points[f[1]],c=points[f[2]];if(!a||!b||!c)continue;const colour=vertices[f[0]].slice(3,6);ctx.fillStyle=colour.length===3?`rgb(${colour.map(x=>Math.round(Math.max(0,Math.min(1,x))*255)).join(',')})`:'#aa92d3';ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.lineTo(c[0],c[1]);ctx.closePath();ctx.fill();}ctx.fillStyle='#aaa0bc';ctx.font=`${11*devicePixelRatio}px sans-serif`;ctx.fillText('Drag to rotate · open the GLB for the full asset',14*devicePixelRatio,h-16*devicePixelRatio);}canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){yaw+=(e.clientX-drag[0])*.01;pitch+=(e.clientY-drag[1])*.01;drag=[e.clientX,e.clientY];draw();}};canvas.onpointerup=()=>drag=null;new ResizeObserver(draw).observe(canvas);requestAnimationFrame(draw);}catch(e){toast('Unable to open the preview. Download the GLB or OBJ to view it.');}}
refresh();setInterval(refresh,4000);
